apiVersion: v1
kind: Namespace
metadata:
  name: eshoponweb-web017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: eshoponweb-web017
  name: webapp
  labels:
    app: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      service: webapp
  template:
    metadata:
      labels:
        app: sample-app
        service: webapp
    spec:
      containers:
        - name: webapp
          image: aistraining.azurecr.io/eshoponwebapp-demo-017:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: ASPNETCORE_ENVIRONMENT
              value: Docker
            - name: WebApiBaseAddress
              value: http://webapi
