apiVersion: v1
kind: Service
metadata:
  namespace: eshoponweb-web017
  name: webapp
  labels:
    app: sample-app
    service: webapp
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: webapp
