name: Contrainer workflow
on: [workflow_dispatch]
env:
  ACR_LOGIN_SERVER: aistraining.azurecr.io
  ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
  ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
  TAG_NAME: eshoponwebapp-demo-017:1.0.0
  IMAGE_NAME: ${{ vars.ACR_LOGIN_SERVER }}/${{ vars.TAG_NAME }}
  RESOURCE_GROUP: rg-017
  CLUSTER_NAME: aks-demo

jobs:
  build-container:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkput source code
        uses: actions/checkout@v7.0.0

      - name: ACR Login
        uses: docker/login-action@v4.4.0
        with:
          registry: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ env.ACR_USERNAME }}
          password: ${{ env.ACR_PASSWORD }}
      
      - name: Build and push Docker image
        run: |
          docker build -f src/Web/Dockerfile -t ${{ env.ACR_LOGIN_SERVER }}/${{ env.TAG_NAME }} .
          docker push ${{ env.ACR_LOGIN_SERVER }}/${{ env.TAG_NAME }}
    # ถ้าใช้ self host runner ไม่ต้อง checkout ซ้ำๆก็ได้ 
  deploy-to-aks:
    needs: build-container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}
      - uses: azure/aks-deploy@v1
        with:
          manifests: | 
            .k8s/deployment.yaml
            .k8s/service.yaml
          images: ${{ env.ACR_LOGIN_SERVER }}/${{ env.TAG_NAME }}
        
      
